### ISSUE TITLE
Mention GPL dependancy?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaStats/StatsFuns.jl#13]
See here:

https://github.com/JuliaStats/Rmath.jl

While if is MIT licensed, it mentions GPL as arms-length doesn't mean your code isn't bound by the GPL(?).

Similarly not here, but you can easily lose track of that one of your dependencies (or of theirs, etc.) is GPL.

**Comment by ararslan** [comment]
Granted I'm not a lawyer, but as I understand it, since this is a *wrapper* for, not a *derived work* of, GPL-licensed software, it isn't bound by the GPL license terms. GPL requires that derived works be licensed under GPL. So if we had code in here that was *ported* from the R source, that would require us to license this package under GPL. But since all of the code here has been written from scratch and simply connects to the Rmath library, we can license it under separate terms (in this case under the terms of the MIT license). In fact, Julia itself has a number of GPL-licensed dependencies, one of which used to be Rmath. So I don't think it's really necessary to mention in this case.

**Comment by nalimilan** [comment]
The current README sounds explicit enough to me. Indeed you cannot really use the package without its GPL dependency, but that doesn't mean the Julia wrapper cannot be licensed as MIT.

**Comment by PallHaraldsson** [comment]
Ther README at:

https://github.com/JuliaStats/Rmath.jl

is explicit yes, but not here. [Both have MIT license, that I guess is legal for wrappers.] As a service to users, I think you should reconsider. If the license, is MIT, for a wrapper to GPL, directly or indirectly, I would want to know, not have to check dependencies recursively.

I could make a PR.

**Comment by johnmyleswhite** [comment]
Yes, we should do this to make things simpler for users, although it adds a considerable amount of maintenance work on our end.

**Comment by PallHaraldsson** [comment]
@ararslan "since this is a wrapper for, not a derived work of, GPL-licensed software, it isn't bound by the GPL license terms."

I think you are in murky waters, Rmath at least, is probably derived.. I'm not sure if this package doesn't work without Rmath. Anyway, just to help users.

@johnmyleswhite what do you mean "maintenance"? I could make the PR. It wouldn't need to be changed?

**Comment by johnmyleswhite** [comment]
Closed by 1d1488ced30d858c51f1c04cbe4ee320108d2ca0

My apologies for not submitting a proper PR: I hit the wrong button when editing.
