### ISSUE TITLE
`tdistinvcdf(0, 0.975)` hangs

### ISSUE THREAD

**Issue by liushang0322** [JuliaStats/StatsFuns.jl#154]
```julia
tdistinvcdf(0.975,0)
```
this maybe have some problems?

**Comment by andreasnoack** [comment]
Please provide more information. Which result are you getting and why do you think it might be wrong? Please also let us know the version of StatsFuns that you are using.

**Comment by liushang0322** [comment]
I'm very sorry, I was too busy yesterday, so I said it very briefly.

I tried two versions, StatsFuns@1.0.1 and StatsFuns@1.1.1, tested in the case of `tdistinvcdf(0,0.975)`, where @1.0.1 is correct to NaN, and @1.1.1 version is There is a stuck phenomenon, this should be a bug

![image](https://user-images.githubusercontent.com/83255448/215630657-fb465c25-71d5-4074-b661-313e991684d4.png)

![image](https://user-images.githubusercontent.com/83255448/215630709-448c87d3-5bf8-41ce-b6e5-ec74b94d3a25.png)

**Comment by ararslan** [comment]
So the problem is not actually with `tdistinvcdf(0.975, 0)` but rather with `tdistinvcdf(0, 0.975)`, and you're saying that the latter produces `NaN` with StatsFuns v1.0.1 and gets stuck with v1.1.1? I can reproduce that, actually:
```
julia> tdistinvcdf(0, 0.975)
^C^C^C^C^C^CWARNING: Force throwing a SIGINT
ERROR: InterruptException:
Stacktrace:
 [1] muladd
   @ ./float.jl:388 [inlined]
 [2] macro expansion
   @ ./math.jl:178 [inlined]
 [3] evalpoly
   @ ./math.jl:177 [inlined]
 [4] expm1b_kernel
   @ ./special/exp.jl:78 [inlined]
 [5] exp_impl
   @ ./special/exp.jl:218 [inlined]
 [6] exp(x::Float64)
   @ Base.Math ./special/exp.jl:326
 [7] _beta_inc_inv(a::Float64, b::Float64, p::Float64, q::Float64)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/hefUc/src/beta_inc.jl:1001
```
The algorithm SpecialFunctions is using for the inverse of the incomplete beta function seems to be struggling. I wonder if we should just be returning `NaN` early when we know the input is malformed.

**Comment by liushang0322** [comment]
> So the problem is not actually with `tdistinvcdf(0.975, 0)` but rather with `tdistinvcdf(0, 0.975)`, and you're saying that the latter produces `NaN` with StatsFuns v1.0.1 and gets stuck with v1.1.1? I can reproduce that, actually:
> 
> ```
> julia> tdistinvcdf(0, 0.975)
> ^C^C^C^C^C^CWARNING: Force throwing a SIGINT
> ERROR: InterruptException:
> Stacktrace:
>  [1] muladd
>    @ ./float.jl:388 [inlined]
>  [2] macro expansion
>    @ ./math.jl:178 [inlined]
>  [3] evalpoly
>    @ ./math.jl:177 [inlined]
>  [4] expm1b_kernel
>    @ ./special/exp.jl:78 [inlined]
>  [5] exp_impl
>    @ ./special/exp.jl:218 [inlined]
>  [6] exp(x::Float64)
>    @ Base.Math ./special/exp.jl:326
>  [7] _beta_inc_inv(a::Float64, b::Float64, p::Float64, q::Float64)
>    @ SpecialFunctions ~/.julia/packages/SpecialFunctions/hefUc/src/beta_inc.jl:1001
> ```
> 
> The algorithm SpecialFunctions is using for the inverse of the incomplete beta function seems to be struggling. I wonder if we should just be returning `NaN` early when we know the input is malformed.

Perhaps this requires a fallback

**Comment by devmotion** [comment]
I tried to figure out the chain of function calls here: `tdistinvcdf` calls `fdistinvcdf`, which then calls `betainvcdf`, which then calls `SpecialFunctions.beta_inc_inv`. More precisely, `tdistinvcdf(nu, p)` ends up calling `SpecialFunctions.beta_inc_inv(1/2, nu/2, 2*min(p, 1 - p))`. That is, in the problematic example `tdistinvcdf(0, 0.975)` we call `SpecialFunctions.beta_inc_inv(1/2, 0, 0.05)`.

**Comment by andreasnoack** [comment]
I don't recall if we generally prefer `NaN`s to exceptions.

**Comment by ararslan** [comment]
I suggested `NaN` because it would be consistent with the behavior prior to #149, i.e. when the function was simply calling into Rmath.

**Comment by devmotion** [comment]
We would get `NaN` automatically if `betainvcdf` (or possibly `SpecialFunctions.beta_inc_inv` - but it seems to be related to https://github.com/JuliaMath/SpecialFunctions.jl/issues/378) would be fixed. Therefore I think the underlying problem here is that
```julia
julia> using StatsFuns

julia> StatsFuns.RFunctions.betainvcdf(0.5, 0.0, 0.05)
1.0

julia> betainvcdf(0.5, 0.0, 0.05) # hangs
```
which we end up calling in this example here (see https://github.com/JuliaStats/StatsFuns.jl/issues/154#issuecomment-1410058432).
If we would return 1.0 as Rmath, then due to https://github.com/JuliaStats/StatsFuns.jl/blob/60dbea0b2ab9e111a76f634af885df290946a621/src/distrs/fdist.jl#L26 `fdistinvcdf(1.0, 0.0, 0.05)` and hence also `tdistinvcdf(0.0, 0.975)` would return `NaN`.
